package io.github.ketao1989.drools

import io.github.ketao1989.drools.PointEntity

rule birthdayPoint
    salience 101
    lock-on-active true
    when
        $pointEntity:PointEntity(birthdayMouth == true)
    then
        $pointEntity.setPoint($pointEntity.getPoint() * 2);
end
//
//rule buyMoneyPoint
//    salience 100
//    lock-on-active true
//    date-effective "2016-01-01 00:00:00"
//    date-expires "2016-05-01 00:00:00"
//    when
//        $pointEntity:PointEntity(buyMoney > 1000)
//    then
//        $pointEntity.setPoint($pointEntity.getPoint() + $pointEntity.getBuyMoney()/100);
//end